name: sync-upstream

on:
  schedule:
    # every day at midnight JST
    - cron: '0 15 * * *'
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  sync:
    name: Sync
    if: ${{ github.repository_owner == 'jcug-oss' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup build env
        run: |
          bin/setup-build-env
      - name: Configure git
        run: |
          bin/configure-git

      - name: Sync submodule
        run: bin/sync-submodule
      - name: Push changes
        run: bin/push-changes "Update upstream"

      - name: Exec po4a-updatepo
        run: bin/exec-po4a-updatepo
      - name: Push changes
        run: bin/push-changes "Update .po files"

      - name: Update translation stats
        run: bin/update-translation-stats
      - name: Push changes
        run: bin/push-changes "Update translation stats"

      - name: Apply tmx
        run: bin/apply-tmx
      - name: Push changes
        run: bin/push-changes "Apply translation memory"

      - name: Machine translate
        if: ${{ env.TRANSLATOR_DEEPL_APIKEY != '' }}
        run: bin/machine-translate
        env:
          TRANSLATOR_DEEPL_APIKEY: ${{ secrets.TRANSLATOR_DEEPL_APIKEY }}
      - name: Push changes
        if: ${{ env.TRANSLATOR_DEEPL_APIKEY != '' }}
        run: bin/push-changes "Add machine translation"
        env:
          TRANSLATOR_DEEPL_APIKEY: ${{ secrets.TRANSLATOR_DEEPL_APIKEY }}
